### PR TITLE
Added callback support for Shiny

### PR DESCRIPTION
**Pull request by jrowen**
Here's a first attempt at using the new bokeh callback functionality in Shiny.  A few items to consider improving:
* The TapTool callback is enabled by default if the `url` param to `make_glyph` is not specified and `shinyMode` is detected in JS.  Would it be better to create a `fig_callback` function that enables the callback and allows specification of additional params?
* A `callback` param was added to `make_glyph` but is not currently used.  Could this be used to allow the user to specify fields to be returned as part of the callback call?  Currently only the data point properties are returned, but the shiny example is a great case where returning additional data (group value instead of fill color) would be useful.
* Any other suggestions/ideas?

### CODE REVIEW

**Comment by hafen** [comment]
This looks great!  I think I've wrapped my head around everything you've done here.

I think it's ok to have the callback enabled when there is no URL and it is in shiny mode.  This makes things very simple.  Do you think there will ever be a case where a user would want to get anything beyond the data for the selected point?  If not, this is good because the remainder of the "callback" can be handled in their shiny app in R - no javascript necessary.  If there are cases where a more advanced user might want to be able to specify their own callback, we could expose `callback` at the figure level as you suggested and it can be either a boolean or a string.  If TRUE, we just use everything you've done here as the default.  What do you think?

Is tap the only callback available in Bokeh right now?  I'm not familiar enough with what they've added.  It would be really nice to have a select callback for box/lasso select.  If something like that is available, it would be good to support it and to think about how to expose different kinds of callback specifications.

Another complicating factor is whether the callback can be different at the layer level vs. figure level.  If all the callback ever does is send the data / index back, then I suppose this doesn't matter.

Whichever route we go with, it would be good to add some documentation, such as with `rbokehOutput` specifying that an input is made available with the same id with `_callback`.

**Comment by jrowen** [comment]
I just pushed an update that enables the `callback` param similar to the `hover` param.  If not specified, it will default to the original dataset.  I think this approach makes more sense, as you'll see from the updated example, one can now filter using the original data.  Let me know what you think.

As far as I can tell, the TapTool is the only [tool](http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh-models-tools) that supports an action.  

I can add some documentation once we agree on the final approach.

**Comment by hafen** [comment]
I think moving this direction is good.  

I've been thinking about it and in anticipation of future callback activity of other types, since this callback is specific to a point being clicked/tapped, I'm thinking we should consolidate both the `url` and `callback` arguments into one argument, `tap` (or maybe there's a better name).  We could handle a string value or column name as is currently handled with with the `url` argument, and for the callback case have the user specify something like `tap = shiny_tap(...)` that will let us know to use your callback logic here.  If we do that, then your latest update is moving us in that direction.  Let's discuss before getting too much deeper.

**Comment by hafen** [comment]
Note that in the current state, a data-less example doesn't work:

```
figure() %>% ly_points(1:10)
```

**Comment by hafen** [comment]
I've been looking at Bokeh and here's an [example of selection callback](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#callbacks-for-selections).

If you run this example in python and examine the html file, you will see clues in the json about how it is done.  For example, the following:

```
  {
    "attributes": {
      "code": "\n  var inds = cb_obj.get('selected')['1d'].indices;\n  var d1 = cb_obj.get('data');\n  var d2 = s2.get('data');\n  d2['x'] = []\n  d2['y'] = []\n  for (i = 0; i < inds.length; i++) {\n    d2['x'].push(d1['x'][inds[i]])\n    d2['y'].push(d1['y'][inds[i]])\n  }\n  s2.trigger('change');\n",
      "tags": [

      ],
      "doc": null,
      "args": {
        "s2": {
          "type": "ColumnDataSource",
          "id": "531b7716-b9dc-4b04-8542-8b45d2823e31"
        }
      },
      "id": "a9ce3bfe-674d-49e2-9732-eb5e4ae265e5"
    },
    "type": "Callback",
    "id": "a9ce3bfe-674d-49e2-9732-eb5e4ae265e5"
  }
```

The "args" specifies `s2` to point to the data source of the second plot.

The ColumnDataSource from the first plot has an attribute that ties this callback to it:

```
      "callback": {
        "type": "Callback",
        "id": "a9ce3bfe-674d-49e2-9732-eb5e4ae265e5"
      }
```

Thus the data source of the first plot is linked to the data source of the second plot.

Looking at this, I think a shiny selection callback is pretty achievable using a similar approach as your tap callback.  That would be pretty cool and open up a lot of possibilities for shiny apps.  What do you think?

**Comment by jrowen** [comment]
I missed the [callback](http://bokeh.pydata.org/en/latest/docs/reference/models.html#bokeh.models.sources.DataSource) on the `DataSource`.  It looks like similar logic could be used to used in this case--I'll take a look.

I like the single param idea (maybe `click` is more familiar to the user).  It seems we'd then have a series of functions like `tap_url`, `tap_callback`, `shiny_callback`, `shiny_select_callback`, etc that are passed to the new param (with no function specified, we'd assume default is `tap_url`).  This would also allow for more specific params related to each action.  

I'll be out of town for a few days and will pick up with things when I'm back.

**Comment by jrowen** [comment]
I was stuck at an airport today and had a little time to work on this.  With this update, the lasso select callback is now working.  The shiny example attempts the mimic the bokeh example you referenced earlier.  Right now I'm using the `code` attribute of the `Callback` model to pass the shiny name suffix for the input object.  This suffix could ultimately be controlled by the user via a param to one of the new `shiny_` tap functions.

**Comment by hafen** [comment]
Nice!  This is very exciting!!

I was writing something up yesterday to spec things out but didn't finish it.  Here's a short version in case you have time to think about it.

We have been focusing on triggering actions through tap / select, but I think we need to think about bokeh plots receiving actions as well for the picture to be complete.  Your new example illustrates that - rather than regenerate the bottom plot each time, it would be great to be able to just update the data source in the plot.

We should focus on making this available intially for `ly_points` while keeping in mind the other layer functions.

## Triggering actions ##

In terms of triggering actions, I think what you have done has this pretty much covered, but we should spec it out a bit more.  For now, we should focus on actions triggered through two types of events:

1. a glyph is clicked / tapped
2. glyphs are selected

Although clicking a point and selecting a point or group of points is similar when thinking about selection (but not when thinking about an action like click to open URL), it might be best to handle them separately.  For each case, we would have the following parameters added to a layer function:

1. `click`: as you suggested, a series of functions could be available `click_url`, `click_callback`, `click_shiny`.  In the case of `click_shiny`, it could probably just be a function with a parameter `id` that identifies the shiny input id to associate clicks with.  In the case of character input, it assumes `click_url`.
2. `select`: similarly for select, there would be `select_callback` and `select_shiny`.

In both cases the `_callback` functions would be an advanced user feature where javascript code is provided and the `_shiny` functions would take care of everything and provide the data as a shiny input for the user to deal with in shiny.

We'd need to handle the case where the layer function splits into multiple column data sources, e.g.

```
figure() %>% ly_points(Sepal.Length, Sepal.Width, glyph = Species, data = iris)
```

In this case, there will be three ColumnDataSources for one data set / layer.  We can simply have the same callback associated with each data source, each triggering the same shiny input, and add an index column to the data prior to it getting split up so that we can maintain an index into the original data set.  The trick would be to consolidate the selections that span more than one data source so that it appears as one in shiny.  We can address this after we've got things working in the simplest case.

The `_callback` and `_shiny` functions should also probably eventually have some kind of optional timeout or debounce parameter as well but we can deal with that later.

## Receiving actions ##

The most logical place to address a bokeh plot receiving an action is through its ColumnDataSources.  

We should explore allowing the `data` argument to `ly_points` (and eventually all layer functions) to optionally be a call to a function, maybe called `shiny_data(id, data = NULL)`, that associates a shiny output id to this data source.  

If `data` is supplied it will be used as the initial / default source, but whenever the associated shiny output is updated, we have some javascript in a custom shiny output type (`renderBokehData` or something) that gets the data into the appropriate json form and puts in the appropriate place of the Bokeh model for the targeted plot.  

For layer functions that transform the data prior to plotting (e.g. `ly_hist`), we would provide the transformation as part of the render function.  This will take some investigation but seems entirely possible.

I think the combination of these two would open up a world of possibilities for interactive vis with shiny, including the ability to link rbokeh with other UI elements / htmlwidgets.  We can start with the "triggering actions", which you've already provided all the technical work for - we just need to map it to a consistent specification.  Let me know what you think.

**Comment by jrowen** [comment]
I like the spec.  To paraphrase, the following would be the implementation steps for triggering and receiving actions, each.

1. Restructure/factor `ly_points` using the `click` and `select` params and create the related functions
2. Support multiple data column sources
3. Enable logic in other supported layers

I'd say go ahead and throw together something for the first step based on the spec.  The design makes sense and should be flexible for future actions.

I like the receiving concept and want think about the design a bit more.  When linking two figures, I'm wondering how much should be left to the user versus handled behind the scenes.  Would it make sense to wrap linked figures in a function call, like `grid_plot`, or pass the source figure as an additional input to the target figure (e.g. either allow `data` to accept a figure or add another param, like `fig`).  In theory, the input figure could be any htmlwidget, so how could this also be supported in a flexible way.

A few areas where the current implementation could be improved:
* The callback JS code could be moved to an R script and/or encapsulated in a JS function if we can find a way to get the rbokeh shiny object name while building the figure. This may be available in a parent environment when the figure is generated as part of a shiny output call.
* The biggest user challenge with the callback is mapping the JS data to a classed R object.  How could we return json to R that could be automatically converted to the original data passed to the callback?  Do we have the shiny callback return an index and then map this to the data?  Do we store the R class for each column of the data and return to shiny with the data?  This logic could be reusable by many widgets using callbacks (e.g. `rhandsontable`).

**Pull request closed without merging**
